version: "3.9"

services:
  spanner-omni-laptop:
    image: us-docker.pkg.dev/spanner-omni/images/spanner-omni:2026.r4-lts
    container_name: spanneromni-laptop
    command: ["start-single-server", "--base-dir=/spanner", "--address=0.0.0.0"]
    ports:
      - "127.0.0.1:15000:15000"
      - "127.0.0.1:15026:15026"
      - "127.0.0.1:5432:5432"
    volumes:
      - omni_laptop_data:/spanner
    deploy:
      resources:
        limits:
          cpus: "4.0"

  spanner-omni-gcp-sim:
    image: us-docker.pkg.dev/spanner-omni/images/spanner-omni:2026.r4-lts
    container_name: spanneromni-gcp-sim
    command: ["start-single-server", "--base-dir=/spanner", "--address=0.0.0.0"]
    ports:
      - "127.0.0.1:25000:15000"
    volumes:
      - omni_gcp_sim_data:/spanner
    profiles: ["local-mesh"]

  spanner-omni-aws-sim:
    image: us-docker.pkg.dev/spanner-omni/images/spanner-omni:2026.r4-lts
    container_name: spanneromni-aws-sim
    command: ["start-single-server", "--base-dir=/spanner", "--address=0.0.0.0"]
    ports:
      - "127.0.0.1:35000:15000"
    volumes:
      - omni_aws_sim_data:/spanner
    profiles: ["local-mesh"]

volumes:
  omni_laptop_data:
  omni_gcp_sim_data:
  omni_aws_sim_data:
